// NextJS
import type { Metadata } from "next";

// Metadata
export const metadata: Metadata = {
    title: "Zeler | Categories",
    description: "B2B SaaS platform for managing your businessGenerated by create next app",
};

export default function CategoriesLayout({ children }: { children: React.ReactNode }) {
    return children;
}