// NextJS
import type { Metadata } from "next";

// Metadata
export const metadata: Metadata = {
    title: "Zeler | Register",
    description: "B2B SaaS platform for managing your businessGenerated by create next app",
};

export default function RegisterLayout({ children }: { children: React.ReactNode }) {
    return (
        <main>
            {children}
        </main>
    );
}
